/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TodoListInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createTodo"
      | "deleteTodo"
      | "getTodoCount"
      | "nextId"
      | "todos"
      | "toggleCompleted"
      | "updateTodo"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createTodo",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteTodo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTodoCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "nextId", values?: undefined): string;
  encodeFunctionData(functionFragment: "todos", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "toggleCompleted",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTodo",
    values: [BigNumberish, string, string, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "createTodo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deleteTodo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTodoCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "todos", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "toggleCompleted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateTodo", data: BytesLike): Result;
}

export interface TodoList extends BaseContract {
  connect(runner?: ContractRunner | null): TodoList;
  waitForDeployment(): Promise<this>;

  interface: TodoListInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createTodo: TypedContractMethod<
    [_title: string, _description: string],
    [void],
    "nonpayable"
  >;

  deleteTodo: TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;

  getTodoCount: TypedContractMethod<[], [bigint], "view">;

  nextId: TypedContractMethod<[], [bigint], "view">;

  todos: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, boolean] & {
        id: bigint;
        title: string;
        description: string;
        completed: boolean;
      }
    ],
    "view"
  >;

  toggleCompleted: TypedContractMethod<
    [_id: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateTodo: TypedContractMethod<
    [
      _id: BigNumberish,
      _title: string,
      _description: string,
      _completed: boolean
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createTodo"
  ): TypedContractMethod<
    [_title: string, _description: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deleteTodo"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getTodoCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "todos"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, boolean] & {
        id: bigint;
        title: string;
        description: string;
        completed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "toggleCompleted"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTodo"
  ): TypedContractMethod<
    [
      _id: BigNumberish,
      _title: string,
      _description: string,
      _completed: boolean
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
